FROM golang:1.16-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY cmd /app/cmd/

COPY pkg/api/*.go /app/pkg/api/

RUN go build -o zula cmd/seeder/main.go

CMD [ "./zula" ]